### PR TITLE
PP-28242 Add sync support for StatsD client

### PR DESCRIPTION
**Pull request by AndLobanov**
https://pushpay.atlassian.net/browse/PP-28242

Add sync support for StatsD client library

### CODE REVIEW

**Comment by kmcc049** [comment]
The formatting in this PR really needs some tidying. Also I'm not sure that switching out tests to verify on send instead of sendasync is the correct approach. Seems better to just duplicate these and make separate ones for the sync methods

**Comment by AndLobanov** [comment]
Formatting looked good locally, space and tabs problem 😄 . 

StatsdExtensionsTests.cs tests only Sync methods for dynamic logging which we don't use. 
All tests are duplicated for sync and async in StatsdTests.cs.

**Comment by nigel-sampson** [comment]
Agree with @kmcc049 on the tests, duplication here would be better.

**Comment by kmcc049** [comment]
Discussed in person with @AndLobanov about the tests. Because of the moving of the extension methods, which was the the way of reversing the deprecation the sync calls the change to the tests is legit.

**Review by kmcc049 — APPROVED** [review]

**Pull request merged**
